# -*- coding: utf-8 -*-
"""google_cloud_storage

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vIn6zwzaUjAEeF1imKKCYBG-smXctDje
"""

import os

from firebase_admin import storage

from config.config import BUCKET_NAME
from config.logger import catch_error
from integrations.firebase.firestore_update_project import update_project_status_and_translated_link_by_id
from integrations.firebase.init_firebase import init_firebase

download_blob_exception = Exception(
    "Error while downloading original file"
)

upload_blob_and_delete_local_file_exception = Exception(
    "Error while uploading translated file"
)

init_firebase()

bucket = storage.bucket(name=BUCKET_NAME)


def download_blob(
    source_blob_name: str,
    destination_file_name: str,
    project_id: str
):
    try:
        blob = bucket.blob(source_blob_name)
        blob.download_to_filename(destination_file_name)
    except Exception as e:
        catch_error(
            tag="downloading",
            error=e,
            project_id=project_id
        )
        raise download_blob_exception


def upload_blob(
    source_file_name: str,
    destination_blob_name: str,
    project_id: str
):
    try:
        blob = bucket.blob(destination_blob_name)
        blob.upload_from_filename(source_file_name)

        blob.make_public()
        public_link = blob.public_url
        print("[upload_blob] Public url for this file:", public_link)
        return public_link

    except Exception as e:
        catch_error(
            tag="uploading",
            error=e,
            project_id=project_id
        )
        raise upload_blob_and_delete_local_file_exception


# source_blob_name = # здесь  'userId/projectId/Original Media File'
# destination_file_name = # здесь 'userId_projectId_Original Media File'

# Хардкод для тестов (выгрузили с облака)
# source_blob_name='XYClUMP7wEPl8ktysClADpuaPIq2/4kIRz5B1JY0GAO1uj0dE/test-video-1min.mp4'
# destination_file_name = 'XYClUMP7wEPl8ktysClADpuaPIq2_4kIRz5B1JY0GAO1uj0dE_test-video-1min.mp4' # уникальное имя файла
# download_blob(bucket, source_blob_name, destination_file_name)

# здесь отрабатывает нейронка
# video path = destination_file_name

# Хардкод для тестов (загрузили обработанно)
# source_file_name = destination_file_name # имя файла на локальной машине после обработки сеткой
# destination_blob_name = source_blob_name[:-4] + '_translated.mp4' # выгружаем обратно с заменённым окончанием
# upload_blob(bucket, source_file_name, destination_blob_name)
